name: Latest blog post workflow
on:
  schedule:
    # 这里的 cron 表达式代表每小时更新一次，你可以根据需要调整
    - cron: '0 * * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # RSS 链接，多个链接用逗号隔开
          feed_list: "https://blog.zhengz.cc/rss.xml"
          max_post_count: 5
          commit_message: "chore: update latest blog posts"
